### ISSUE TITLE
More verbose docs

### ISSUE THREAD

**Issue by muschellij2** [junruidi/ActCR#1]
We were looking to use this package, but it's unclear what some output are:
https://github.com/junruidi/ActCR/blob/master/R/ActCosinor.R#L13

**Comment by junruidi** [comment]
Hey John, good to hear from you and know that you guys are working on it. I have updated the manual. Please let me know if they make sense. Some details can also be found here: https://tbiomed.biomedcentral.com/articles/10.1186/1742-4682-11-16
