### ISSUE TITLE
IS_long did not calculate IS for an individual broken up by day.

### ISSUE THREAD

**Issue by agarduno93** [junruidi/ActCR#7]
IS_long is performing differently than IV_long. It seems like IS_long is returning one value over all seven days for this person, whereas IV_long gives IV for each day separately. I would like to use IS_long to get separate IS values per day. This seems to be an error.

> is_subj = IS_long(count.data = whi_file_t2, window = 1, method = "average")
> is_subj
           ID      IS_1
XXXXX  0.2039345

iv_subj = IV_long(count.data = whi_file_t2, window = 1, method = "average")
> iv_subj
      ID Day      IV_1
XXXX   1 1.3055884
XXXX  2 0.9574416
XXX  3 1.0852362
XXXX   4 1.3747254
XXXX   5 1.2967164
XXXX  6 1.3235332
XXXX   7 1.0998867

**Comment by junruidi** [comment]
IT IS NOT AN ERROR.
By definition,  interdaily stability is a normalized measurement of variations of activity across days (hence, inter-day). It is a measurement of whether someone's day to day activity are consistent or not. Therefore, you will not "get separate IS values per day". Please refer to Witting's 1990 paper.
